title: Prabakaran R
url: "https://rpkarandev.github.io/"
baseurl: "/"

theme: minima
markdown: kramdown
#ins_logo: "./bits-logo.png"

minima:
  skin: classic
  custom_css:
    - assets/style.css


tracking_id: #

footer: yes
footer_url: "https://github.com/rpkarandev"
footer_text: ""

sass:
    style: compressed
    sass_dir: _sass

scholar:
  style: modern-language-association
  bibliography_template: bib
#nav:
#  - name: "Publication"
#   link: "publication"

# - name: "Resume"
#   link: "resume.pdf"
# - name: "Contact"
#   link: "contact"

