#!/usr/bin/env python3
"""Refresh _data/scholar.yml from Google Scholar.

Run this locally (from a trusted IP) whenever you want to update the citation
metrics and per-paper counts shown on the Publications page, then commit the
regenerated _data/scholar.yml.

    pip install -r tools/requirements.txt
    python tools/update_scholar.py
    git add _data/scholar.yml && git commit -m "Update Scholar metrics"

Google Scholar has no official API and rate-limits scraping; if it fails,
wait a while and retry, or run from a different network.
"""
import datetime
import os
import sys

import yaml
from scholarly import scholarly

AUTHOR_ID = "7aAKswUAAAAJ"  # https://scholar.google.com/citations?user=7aAKswUAAAAJ
OUT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "_data", "scholar.yml"))


def main():
    print(f"Fetching Google Scholar profile {AUTHOR_ID} ...")
    author = scholarly.search_author_id(AUTHOR_ID)
    author = scholarly.fill(author, sections=["basics", "indices", "counts", "publications"])

    cites_per_year = author.get("cites_per_year", {}) or {}
    cites_per_year = {int(y): int(c) for y, c in sorted(cites_per_year.items())}

    articles = []
    for pub in author.get("publications", []):
        bib = pub.get("bib", {})
        title = (bib.get("title") or "").strip()
        if not title:
            continue
        articles.append({
            "title": title,
            "year": str(bib.get("pub_year", "") or ""),
            "citations": int(pub.get("num_citations", 0) or 0),
        })
    articles.sort(key=lambda a: a["citations"], reverse=True)

    data = {
        "updated": datetime.date.today().isoformat(),
        "total_citations": int(author.get("citedby", 0) or 0),
        "h_index": int(author.get("hindex", 0) or 0),
        "i10_index": int(author.get("i10index", 0) or 0),
        "citations_per_year": cites_per_year,
        "articles": articles,
    }

    header = (
        "# Auto-generated by tools/update_scholar.py - do not edit by hand.\n"
        "# Refresh:  python tools/update_scholar.py   (then commit this file)\n"
    )
    with open(OUT, "w") as f:
        f.write(header)
        yaml.safe_dump(data, f, sort_keys=False, allow_unicode=True, default_flow_style=False)

    print(f"Wrote {OUT}")
    print(f"  total_citations={data['total_citations']} h_index={data['h_index']} "
          f"i10_index={data['i10_index']} articles={len(articles)}")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:  # noqa: BLE001
        print(f"ERROR: {exc}", file=sys.stderr)
        print("Google Scholar may be rate-limiting. Wait and retry, or use a different network.",
              file=sys.stderr)
        sys.exit(1)
